<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Bookings\**" />
    <Compile Remove="Events\**" />
    <EmbeddedResource Remove="Bookings\**" />
    <EmbeddedResource Remove="Events\**" />
    <None Remove="Bookings\**" />
    <None Remove="Events\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="EventManagerAppFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="lpwkgf2q.sll~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\EventManager.Domain\EventManager.Domain.csproj" />
    <ProjectReference Include="..\..\SharedLibs\EventManager.DTOs\EventManager.DTOs.csproj" />
    <ProjectReference Include="..\..\SharedLibs\Shared\EventManager.Shared.csproj" />
    <ProjectReference Include="..\EventManager.Tests.Abstractions\EventManager.Tests.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>