<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\EventManager.Domain\EventManager.Domain.csproj" />
    <ProjectReference Include="..\..\SharedLibs\EventManager.DTOs\EventManager.DTOs.csproj" />
    <ProjectReference Include="..\..\SharedLibs\EventsManager.Failures\EventsManager.Failures.csproj" />
    <ProjectReference Include="..\..\SharedLibs\Shared\EventsManager.Shared.csproj" />
    <ProjectReference Include="..\EventManager.DataAccess.Abstractions\EventManager.Repositories.csproj" />
  </ItemGroup>
</Project>
