global:
  scrape_interval: 15s

scrape_configs:
  - job_name: events-local
    static_configs:
      - targets: [ "host.docker.internal:5242"]
    metrics_path: /metrics
  - job_name: events-docker
    static_configs:
      - targets: 
        - events-service:8080
    metrics_path: /metrics

  - job_name: bookings-service
    static_configs:
      - targets: [ "host.docker.internal:5265"]
    metrics_path: /metrics
  - job_name: bookings-docker
    static_configs:
      - targets: 
        - bookings-service:8080
    metrics_path: /metrics

  - job_name: users-service
    static_configs:
      - targets: ["host.docker.internal:5293"]
    metrics_path: /metrics
  - job_name: users-docker
    static_configs:
      - targets: 
        - users-service:8080
    metrics_path: /metrics
