{
 "title": "Users service",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Invalid login attempts",
   "type": "heatmap",
   "description": "This panel analyzes the number of invilid attempts to login. A high frequency of  invilid attempts  may indicate hackers attack.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_bucket{job=\"users-docker\", http_response_status_code=\"404\", http_route=\"api/auth/login\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login dublicates",
   "type": "stat",
   "description": "This panel analyzes the number of exceptions arising from user registrations with duplicate usernames. A high frequency of such exceptions may indicate a need to review the registration policy.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_exceptions_total{error_type=\"UniqueConstraitException\", job=\"users-docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New users",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{http_request_method=\"POST\", job=\"users-docker\", http_response_status_code=\"204\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}