{
 "title": "Users service",
 "time": { "from": "2026-08-01T03:25:54.435Z", "to": "2026-08-01T10:54:57.106Z" },
 "panels": [
  {
   "title": "Error Rate ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__rate_interval])) / \r\nsum(rate(http_server_request_duration_seconds_count[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login dublicates",
   "type": "timeseries",
   "description": "This panel analyzes the number of exceptions arising from user registrations with duplicate usernames. A high frequency of such exceptions may indicate a need to review the registration policy.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "dotnet_exceptions_total{error_type=\"UniqueConstraitException\", job=\"users-docker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{http_request_method=\"POST\", job=\"users-docker\", http_response_status_code=\"204\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid login attempts",
   "type": "timeseries",
   "description": "This panel analyzes the number of invilid attempts to login. A high frequency of  invilid attempts  may indicate hackers attack.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_server_request_duration_seconds_bucket{job=\"users-docker\", http_response_status_code=\"404\", http_route=\"api/auth/login\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}