<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SharedLibs\Shared.AspNet\Shared.AspNet.csproj" />
    <ProjectReference Include="..\..\..\SharedLibs\Shared.Enums\Shared.Enums.csproj" />
    <ProjectReference Include="..\..\..\SharedLibs\Shared.Infrastracture.Kafka\Shared.Infrastracture.Kafka.csproj" />
    <ProjectReference Include="..\..\..\SharedLibs\Shared.Infrastructure.Security\Shared.Infrastructure.Security.csproj" />
    <ProjectReference Include="..\..\..\SharedLibs\Shared.Messaging\Shared.Messaging.csproj" />
    <ProjectReference Include="..\Events.Application\Events.Application.csproj" />
    <ProjectReference Include="..\Events.Infrastracture.Postgre\Events.Infrastracture.csproj" />
    <ProjectReference Include="..\Events.Infrastracture.Postgre\Events.Infrastracture.Postgre.csproj" />
  </ItemGroup>

</Project>
